### PR TITLE
FileTransfer Wifi support

### PR DESCRIPTION
**Pull request by antonio-openroad**
Testing FileTransfer Wifi support (Ble support disabled in this version)

### CODE REVIEW

**Comment by tannewt** [comment]
Code looks good. The APK doesn't get past the searching screen for me though.

**Comment by antonio-openroad** [comment]
I tested it with the latest firmware (adafruit-circuitpython-adafruit_feather_esp32s2_tft-en_US-20220727-88102d1.uf2) and a Pixel 3a and it works for me.
Can you check that you are using the "Glider Wifi" app. Maybe you also have installed on your phone the Bluetooth version that is called "Glider"

**Comment by tannewt** [comment]
Ya, it is labeled glider wifi and has the wifi symbol in the middle of the searching animation. Still doesn't find anything though.

**Comment by tannewt** [comment]
@antonio-openroad and I met. We found a weird case where the Glider build works if I use another app to do the mdns search first. He's going to look for some missing init calls or permissions.

**Comment by tannewt** [comment]
The new apk works even after a restart!

**Review by tannewt — APPROVED** [review]

**Pull request merged**
