### PR TITLE
FileTransfer Library

### PR DESCRIPTION
**Pull request by antonio-openroad**
Refactored FileTransfer code into a separate module to be reused by PyLeap Android
Fixed keyboard covering text area when editing a file
Updated Android libraries

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Is there a way that the file transfer library could be in its own repo? That way it wouldn't need to be copied into both glider and pyleap. I don't know if android has a way to pull from a repo or you could use git submodules to have git pull it in.

**Comment by antonio-openroad** [comment]
> Is there a way that the file transfer library could be in its own repo? That way it wouldn't need to be copied into both glider and pyleap. I don't know if android has a way to pull from a repo or you could use git submodules to have git pull it in.

Yes, It would be better if we use a common repo because right now I have to update both projects every time the library is updated. 
Do you want to create the repo?

**Comment by tannewt** [comment]
Done! https://github.com/adafruit/FileTransfer-For-Android

**Review by tannewt — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
